--Added Clean SQL since the ./flyway clean migrate and/or ./flyway clean
-- is not dropping current objects
DROP TABLE IF EXISTS  EDS.REFT_BRAND_DIM;
DROP TABLE IF EXISTS  EDS.REFT_GROWTH_PLATFORM_DIM;
DROP TABLE IF EXISTS  EDS.REFT_SERVICE_LINE_DIM;
DROP TABLE IF EXISTS  EDS.REFT_PRACTICE_DIM;
DROP TABLE IF EXISTS  EDS.REFT_SERVICE_AREA_DIM;
DROP TABLE IF EXISTS  EDS.REFT_JOB_ROLE_DIM;
DROP TABLE IF EXISTS  EDS.REFT_SPECIALTY_DIM;
DROP TABLE IF EXISTS  EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC;
--DROP VIEW EDS.VW_JRS_DIM;
COMMIT;