-- Create EDS table
CREATE TABLE EDS.REFT_BRAND_DIM (
      BRAND_ID       INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   BRAND_CD                 CHAR    (8)
  ,   BRAND_NM                 VARCHAR (255)
  ,   BRAND_DESC               VARCHAR (255)
  )
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE EDS.REFT_BRAND_DIM ADD CONSTRAINT REFT_BRAND_DIM_PK PRIMARY KEY (BRAND_ID);

--Create UNIQUE INDEX based on the natural key
CREATE UNIQUE INDEX EDS.REFT_BRAND_DIM_UX1 
    ON EDS.REFT_BRAND_DIM (
      BRAND_CD  ASC
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE EDS.REFT_BRAND_DIM IS 'Describes the Business Unit as defined by the IBM organization, e.g. GBS';

--Add comments to the columns
COMMENT ON COLUMN EDS.REFT_BRAND_DIM.BRAND_ID IS 'Surrogate key for EDS.REFT_BRAND_DIM.';
COMMENT ON COLUMN EDS.REFT_BRAND_DIM.BRAND_CD IS 'Brand code.';
COMMENT ON COLUMN EDS.REFT_BRAND_DIM.BRAND_NM IS 'Brand name (short description)';
COMMENT ON COLUMN EDS.REFT_BRAND_DIM.BRAND_DESC IS 'Brand long description';
