-- Create EDS table
CREATE TABLE EDS.REFT_SERVICE_AREA_DIM (
      SERVICE_AREA_ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   SERVICE_AREA_CD          CHAR    (8) NOT NULL
  ,   SERVICE_AREA_NM          VARCHAR (255) NOT NULL
  ,   SERVICE_AREA_DESC        VARCHAR (255)
  ,   BUSINESS_UNIT_CD         CHAR    (8)
  ,   PRACTICE_CD              CHAR    (15)
  )
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE EDS.REFT_SERVICE_AREA_DIM ADD CONSTRAINT REFT_SERVICE_AREA_DIM_PK PRIMARY KEY (SERVICE_AREA_ID);

--Create UNIQUE INDEX based on the natural key
CREATE UNIQUE INDEX EDS.REFT_SERVICE_AREA_DIM_UX1 
    ON EDS.REFT_SERVICE_AREA_DIM (
      SERVICE_AREA_CD  ASC
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE EDS.REFT_SERVICE_AREA_DIM IS 'The Service Area to which the JR/S is aligned on the Line of Business JR/S short list.';

--Add comments to the columns
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.SERVICE_AREA_ID IS 'Surrogate key for EDS.REFT_SERVICE_AREA_DIM.';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.SERVICE_AREA_CD IS 'Service Area code';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.SERVICE_AREA_NM IS 'Service Area name (short description)';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.SERVICE_AREA_DESC IS 'Service Area description';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.BUSINESS_UNIT_CD IS 'Business Unit code';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_DIM.PRACTICE_CD IS 'Practice code';