-- Create EDS table
CREATE TABLE EDS.REFT_JOB_ROLE_DIM (
      JOB_ROLE_ID              INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   JOB_ROLE_CD              CHAR    (8) NOT NULL
  ,   JOB_ROLE_NM              VARCHAR (255) NOT NULL
  ,   JOB_ROLE_DESC            VARCHAR (255)
  )
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE EDS.REFT_JOB_ROLE_DIM ADD CONSTRAINT REFT_JOB_ROLE_DIM_PK PRIMARY KEY (JOB_ROLE_ID);

--Create UNIQUE INDEX based on the natural key
CREATE UNIQUE INDEX EDS.REFT_JOB_ROLE_DIM_UX1 
    ON EDS.REFT_JOB_ROLE_DIM (
      JOB_ROLE_CD  ASC
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE EDS.REFT_JOB_ROLE_DIM IS 'The job role is adopted from the existing IGS structure and reflects the work content.';

--Add comments to the columns
COMMENT ON COLUMN EDS.REFT_JOB_ROLE_DIM.JOB_ROLE_ID IS 'Surrogate key for EDS.REFT_JOB_ROLE_DIM.';
COMMENT ON COLUMN EDS.REFT_JOB_ROLE_DIM.JOB_ROLE_CD IS 'Job Role code';
COMMENT ON COLUMN EDS.REFT_JOB_ROLE_DIM.JOB_ROLE_NM IS 'Job Role name (short description)';
COMMENT ON COLUMN EDS.REFT_JOB_ROLE_DIM.JOB_ROLE_DESC IS 'Job Role description';