-- Create EDS table
CREATE TABLE EDS.REFT_SPECIALTY_DIM (
      SPECIALTY_ID             INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   SPECIALTY_CD             CHAR    (8) NOT NULL
  ,   SPECIALTY_NM             VARCHAR (255) NOT NULL
  ,   SPECIALTY_DESC           VARCHAR (255) 
  )
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE EDS.REFT_SPECIALTY_DIM ADD CONSTRAINT REFT_SPECIALTY_DIM_PK PRIMARY KEY (SPECIALTY_ID);

--Create UNIQUE INDEX based on the natural key
CREATE UNIQUE INDEX EDS.REFT_SPECIALTY_DIM_UX1 
    ON EDS.REFT_SPECIALTY_DIM (
      SPECIALTY_CD  ASC
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE EDS.REFT_SPECIALTY_DIM IS 'A unique talent accepted in the labor market.  The specialty is the business or technical work environment.';

--Add comments to the columns
COMMENT ON COLUMN EDS.REFT_SPECIALTY_DIM.SPECIALTY_ID IS 'Surrogate key for EDS.REFT_SPECIALTY_DIM.';
COMMENT ON COLUMN EDS.REFT_SPECIALTY_DIM.SPECIALTY_CD IS 'Specialty code';
COMMENT ON COLUMN EDS.REFT_SPECIALTY_DIM.SPECIALTY_NM IS 'Specialty  name (short description)';
COMMENT ON COLUMN EDS.REFT_SPECIALTY_DIM.SPECIALTY_DESC IS 'Specialty description';