-- Create EDS table
CREATE TABLE EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC (
      SA_JRS_ID                INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER )
  ,   SERVICE_AREA_CD          CHAR    (8) NOT NULL
  ,   JOB_ROLE_CD              CHAR    (8) NOT NULL
  ,   SPECIALTY_CD             CHAR    (8) NOT NULL
  )
  DATA CAPTURE NONE 
  COMPRESS NO;

--Alter table to add primary key for Surrogate Id
ALTER TABLE EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC ADD CONSTRAINT REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC_PK PRIMARY KEY (SA_JRS_ID);

--Create UNIQUE INDEX based on the natural key
CREATE UNIQUE INDEX EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC_UX1 
    ON EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC (
      SERVICE_AREA_CD ASC
    , JOB_ROLE_CD     ASC
    , SPECIALTY_CD    ASC
    )
    MINPCTUSED 0
    DISALLOW REVERSE SCANS
    PAGE SPLIT SYMMETRIC
    COLLECT SAMPLED DETAILED STATISTICS
    COMPRESS NO;

--Add comments to the table
COMMENT ON TABLE EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC IS 'An association table linking Service Areas to Job Role / Specialties';

--Add comments to the columns
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC.SA_JRS_ID IS 'Surrogate key for EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC.';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC.SERVICE_AREA_CD IS 'Service Area code';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC.JOB_ROLE_CD IS 'Job Role code';
COMMENT ON COLUMN EDS.REFT_SERVICE_AREA_JOB_ROLE_SPECIALTY_ASSOC.SPECIALTY_CD IS 'Specialty code';
